### ISSUE TITLE
queries not opening

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-org/vars-gridview#23]
Many queries are failing to open for example, Pennatulacea:

```
Traceback (most recent call last):
  File "/Users/lonny/.pyenv/versions/3.11.4/lib/python3.11/site-packages/vars_gridview/scripts/run.py", line 320, in _do_query
    self.image_mosaic = ImageMosaic(
                        ^^^^^^^^^^^^
  File "/Users/lonny/.pyenv/versions/3.11.4/lib/python3.11/site-packages/vars_gridview/lib/image_mosaic.py", line 185, in __init__
    moment_timestamp = get_timestamp(video_start_timestamp, recorded_timestamp, elapsed_time_millis, timecode)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lonny/.pyenv/versions/3.11.4/lib/python3.11/site-packages/vars_gridview/lib/util.py", line 39, in get_timestamp
    hours, minutes, seconds, _ = map(int, timecode.split(":"))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '09-35-24-28'
```

This is also happening for midwater concepts like Mitrocoma cellularia and others.

**Comment by lonnylundsten** [comment]
Following up on this....I must have updated something in homebrew which has changed the way pymssql functions. I have tried numerous things to no avail. gridview is still working on my Intel Mac Pro, so I will use that in the interim. Will keep you updated on a solution for my m1 laptop.

**Comment by lonnylundsten** [comment]
different error on my Intel Mac when trying to open Pennatulacea: 

```
Traceback (most recent call last):
  File "/Users/lonny/.pyenv/versions/3.11.4/lib/python3.11/site-packages/vars_gridview/scripts/run.py", line 320, in _do_query
    self.image_mosaic = ImageMosaic(
                        ^^^^^^^^^^^^
  File "/Users/lonny/.pyenv/versions/3.11.4/lib/python3.11/site-packages/vars_gridview/lib/image_mosaic.py", line 185, in __init__
    moment_timestamp = get_timestamp(video_start_timestamp, recorded_timestamp, elapsed_time_millis, timecode)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lonny/.pyenv/versions/3.11.4/lib/python3.11/site-packages/vars_gridview/lib/util.py", line 39, in get_timestamp
    hours, minutes, seconds, _ = map(int, timecode.split(":"))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '09-35-24-28'
```

**Comment by lonnylundsten** [comment]
The above issue is still occurring and unrelated to the FreeTDS incompatibility mentioned in #22.

**Comment by kevinsbarnard** [comment]
From VARS meeting:
Issue is with tape timecodes with dashes (e.g., `09-35-24-28`) instead of colons. @hohonuuli suggests updating these all in VARS for consistency. For now, I'll add a patch that can handle either.

**Comment by hohonuuli** [comment]
Fixed:

```sql
UPDATE imaged_moments
SET timecode = REPLACE(timecode, '-', ':')
WHERE timecode LIKE '%-%'
```
