### ISSUE TITLE
error when deleting several localizations at once

### ISSUE THREAD

**Issue by kevinsbarnard** [mbari-org/vars-gridview#3]
Imported from https://bitbucket.org/mbari/gridview/issues/9/error-when-deleting-several-localizations
---
While using grid view, I keep getting the error pasted below when I try to delete several localizations at once. Once I get this error, I can’t delete any of the ones I’ve selected. The solution is to re-run the query and then I can select and delete the localizations.

    Traceback (most recent call last):

    File "/Users/lonny/.pyenv/versions/3.11.1/lib/python3.11/site-packages/vars_gridview/scripts/run.py", line 399, in move_to_discard

    self.image_mosaic.delete_selected()

    File "/Users/lonny/.pyenv/versions/3.11.1/lib/python3.11/site-packages/vars_gridview/lib/image_mosaic.py", line 384, in delete_selected

    rect.localization.delete()

    File "/Users/lonny/.pyenv/versions/3.11.1/lib/python3.11/site-packages/vars_gridview/lib/annotation.py", line 159, in delete

    delete_bounding_box(self.association_uuid)

    File "/Users/lonny/.pyenv/versions/3.11.1/lib/python3.11/site-packages/vars_gridview/lib/m3/operations.py", line 123, in delete_bounding_box

    response.raise_for_status()

    File "/Users/lonny/.pyenv/versions/3.11.1/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://m3.shore.mbari.org/anno/v1/associations/1db9d5ef-e6b8-4a1d-5a69-8063c740da1e 

This just happened again and when I re-ran the query for these dives, the localizations had actually already been deleted. Maybe they are being deleted but it's not reflected in gridview? Its not super consistent, will monitor more closely.

**Comment by kevinsbarnard** [comment]
I haven't been able to reproduce this; needs further investigation.
